### ISSUE TITLE
LGPL Compatible Licensing

### ISSUE THREAD

**Issue by Danielku15** [ioctlLR/NVorbis#12]
Hi there. 

I would like to extend my MIDI synthesis library (https://github.com/CoderLine/alphaSynth) with SoundFont3 support. In SoundFont3 the audio samples are OGG Vorbis encoded. 

Your library has quite a clean code base which I would like to adapt for my library. Since I'm compiling my library also to JavaScript I will need to make several architectural and code-style adjustments to the code. 

The main problem is that your library is licensed under MS-PL which is not compatible with the LGPL license I am publishing my library with. With this issue I would like to ask for permission to license and redistribute your source code under LGPL. Of course I will add your name to the copyright notice and mention this project in my readme.

**Comment by ioctlLR** [comment]
I'd need to get comments from the handful of other contributors before granting permission, but I don't personally have an issue with it.

**Comment by Danielku15** [comment]
If you could organize the permission from the other contributors, that would be great. 

I've already adapted the source code into my project and it's working great. I cleaned a lot of stuff from the code which I do not fully need or appeared to be a bit too complex for my needs. Since I'm compiling my library also to JavaScript I need to keep the source clean and simple not have no performance problems or an unnecessarily big payload.  

Once I got your permission I would ensure all copyright notices are correct and publish the source to Github.

**Comment by Unit158** [comment]
OpenRA requires this as well.

**Comment by ioctlLR** [comment]
@renaudbedard, @jjxtra, @ToddBertaOldham, @dan200, @yyagi8864, @mrhelmut 

Anyone have any issues with adding LGPL to the project?  Other options?

**Comment by jjxtra** [comment]
If you are bringing NVorbis into an LGPL project, I don't see a need to do anything, the Microsoft license if pretty permissive. If you are wanting to bring LGPL code into this project however, that's a different story.

**Comment by Danielku15** [comment]
I lately changed my library license to Mozilla Public License 2.0 hence GPL compatibility is not really an issue anymore to me. I still need to check what it means to "integrate/adapt" MS-PL code into a MPL-2.0 project as this "compatibiltiy between OSS licenses" is really tricky. 

I will try to keep all copyright notices in place and extend my "Thanks to..." section. I will definitly try to keep the source as close to the original as possible and just use the low level parts I need for the audio sample decoding to keep my library footprint small.

**Comment by ioctlLR** [comment]
Hmmm...  @Danielku15 it looks like we can cancel this issue, given your change to MPL2.  I can't say that the two licenses are actually compatible, but this issue is for LGPL and I don't think we really need it any more.

I would consider relicensing to MIT or BSD 1-clause if everyone wanted to do so.

**Comment by ToddBertaOldham** [comment]
I’d be fine relicensing to MIT or BSD if everyone else is okay with it.

**Comment by ioctlLR** [comment]
See [#1 in the new repository](https://github.com/NVorbis/NVorbis/issues/1).
