### ISSUE TITLE
Minimum data size

### ISSUE THREAD

**Issue by suzdalnitski** [ioctlLR/NVorbis#14]
It would be great if you could add some sort of validation for minimum data size... I've spent the entire day stepping through the code just to discover that data smaller than 32kb is not supported.
Thanks.

**Comment by ioctlLR** [comment]
Could you send me a link to an example file?  I'm not aware of a minimum data size.

Better yet, since you've already stepped through it, you could maybe point me to where the 32kb requirement exists?  I did not intentionally put in such a requirement.

**Comment by suzdalnitski** [comment]
Hi Andrew, thank you for your reply.

I'm trying to implement ogg streaming, and using the Stream constructor:

**Comment by ioctlLR** [comment]
#23 will fix this by removing the complexity of the BufferedStream/StreamReadBuffer.

**Comment by ioctlLR** [comment]
If you try latest from source, this should be fixed.

**Comment by ioctlLR** [comment]
Fix released, see [v0.9.1](https://github.com/NVorbis/NVorbis/releases/tag/v0.9.1).
