### ISSUE TITLE
.Net Standard

### ISSUE THREAD

**Issue by ToddBertaOldham** [ioctlLR/NVorbis#15]
Any chance of moving NVorbis to .Net Standard? I built the project for version 2.0 without any compilation errors. However, I have not yet tested it for any run time issues. Earlier versions may also be possible but they will require a bit of work. Certain things such as binary serialization are not available until 2.0. I'd be happy to help with a bit of updating.
  
Edit: I created a fork of the project with an updated csproj that targets .Net Standard 2.0 and .Net Framework 3.5. The test app ran just as it should after deleting the old NAudio test from when NAudio support was included in the project. It seems the library works perfectly fine with .Net Standard. It just needs some work to run on earlier versions if that is desired.
  
Edit 2: I can submit a pull request if you're interested. A bit of work may be necessary to get Nuget working with it.

**Comment by feliwir** [comment]
Any updates?

**Comment by ToddBertaOldham** [comment]
I wasn’t but I suppose I can create an unofficial package considering this may never be updated and I too want a Nuget package. It’s extremely late where I am so I’ll look into it tomorrow. It should be easy and I can't imagine there would be any issues with creating an unofficial package.

**Comment by ioctlLR** [comment]
@ToddBertaOldham, what if I made you a contributor so you can update mainline / nuget yourself? :)

Work and life have really put a damper on my open source pursuits, and I don't foresee any improvement anytime soon...

**Comment by ToddBertaOldham** [comment]
That would be great! I have my own work stuff going on and my knowledge of Vorbis decoding is limited but I’d be happy to help keep this alive where I can. I have a few things left to do like updating the OpenTKSupport project format and replacing the Nuget package generation, but I could have this updated soon. Stuff like earlier .Net Standard support I’ll have to save for another day.

**Comment by ToddBertaOldham** [comment]
NVorbis 0.8.6 with .Net Standard 2.0 support has been [published](https://www.nuget.org/packages/NVorbis/)! I added it as reference to my own .Net Standard project and it works without any issues. I'll go ahead and close this but @ioctlLR when you have a moment could you please add me as an owner of the OpenTKSupport package as well? I changed it to use the official OpenTK package now that it’s being updated again. Thanks.

**Comment by feliwir** [comment]
@toddbertaoldham can you please join the nvorbis gitter channel?
