### ISSUE TITLE
Help with network streaming

### ISSUE THREAD

**Issue by observer1** [ioctlLR/NVorbis#18]
Hi
I have this code:

if(webResponse == null) {
	HttpWebRequest request = (HttpWebRequest)WebRequest.Create(cUri);
	webResponse = request.GetResponse();
	stream = webResponse.GetResponseStream();
	vorbisReader = new VorbisReader(stream, false);
	timestamp = 0 ;
}

Im getting this execption on VorbisReader Constructor:

System.InvalidOperationException: Cannot seek to beyond the end of the buffer!  Discard some bytes.

The server sends the headers first as discussed in other issue
The code is running in mono on linux.
Can somebody help me with this?

**Comment by ioctlLR** [comment]
Please create a new issue with URI of the source stream and your example code if this is still an issue.
