### ISSUE TITLE
Opus ?

### ISSUE THREAD

**Issue by StefH** [ioctlLR/NVorbis#19]
Any plans on adding **opus** support ?

**Comment by ioctlLR** [comment]
Opus is a completely different codec and will not be added to NVorbis.
Sorry.

**Comment by ToddBertaOldham** [comment]
I had someone ask me this question not too long and I pointed them towards [this library](https://github.com/lostromb/concentus). I have not used it myself, but it seems like it would provide the opus functionality you are looking for. If there’s nothing else to discuss I’ll go ahead and close this.

**Comment by StefH** [comment]
@ToddBertaOldham 
I'm already using this one, however it lacks seek support...
