### ISSUE TITLE
Fail to find OggS in FindNextPageHeader()

### ISSUE THREAD

**Issue by yyagi8864** [ioctlLR/NVorbis#20]
About NVorbis/Ogg/OggContainerReader.cs: PageHeader FindNextPageHeader()...

By some RIFF-chunked vorbis file like below,
_stream.Position does not increment from 0x14, and fail to find OggS.
(because "Og" (a piece of OggS) are there in 0x14)

As the result, the constructor of VorbisReader() raises
InvalidDataException("Could not determine container type!").

Although RIFF-chunked Vobis file may out of scope, but I hope some improvements.

```
      +0 +1 +2 +3 +4 +5 +6 +7 +8 +9 +A +B +C +D +E +F  0123456789ABCDEF
-----------------------------------------------------------------------
0000: 52 49 46 46 06 E4 25 00-57 41 56 45 66 6D 74 20  RIFF..%.WAVEfmt 
0010: 1A 00 00 00 4F 67 02 00 80 BB 00 00 20 4E 00 00  ....Og...... N..
0020: 01 00 10 00 08 00 01 02-02 20 31 12 01 20 64 61  ......... 1.. da
0030: 74 61 CC E3 25 00 4F 67-76 53 00 02 00 00 00 00  ta..%.OggS......
0040: 00 00 00 00 00 00 00 00-00 00 00 00 C0 C1 FA 17  ................
0050: 01 1E 01 76 6F 72 62 69-73 00 00 00 00 02 80 BB  ...vorbis.......
(snip)
```

http://27.120.112.19/dgb.wav.zip is the real file. (Be careful, it may crash your file explorer. It seems some ACM codec invokes Access Violation)

**Comment by ioctlLR** [comment]
This should be fixed now.
