### ISSUE TITLE
Add support for Ogg "Skeleton" metadata

### ISSUE THREAD

**Issue by ioctlLR** [ioctlLR/NVorbis#3]
See specs on xiph.org.  Should be able to piggy-back on existing Ogg reader...  Add a new interface type to expose details?

**Comment by rcarubbi** [comment]
I'm trying to read a .oga file with NVorbis but I'm reveiving the message "Could not determine container type!" on constructor of VorbisReader.
Is this problem due to this issue?

**Comment by ioctlLR** [comment]
I'm not sure. Can you upload the file somewhere so I can look at it?
Message me privately with the link if you'd like.

**Comment by rcarubbi** [comment]
https://bcattachmentsprod.blob.core.windows.net/636258816000000000/HBdjmtt2OrA/file_13.oga

**Comment by rcarubbi** [comment]
My scenario is...

I want to get audio from telegram (that sends in oga) and send to bing speech api to recognize voice.
But bing speech API only supports wav format.

:(

**Comment by ioctlLR** [comment]
That link gives a 404...  Do you have another one?

**Comment by rcarubbi** [comment]
sorry, 

another one: 
https://bcattachmentsprod.blob.core.windows.net/636261588000000000/KdKGuTwY9nA/file_130.oga

**Comment by ioctlLR** [comment]
OK, that one worked.  It's an OPUS file, which NVorbis cannot decode.  You
might try https://github.com/lostromb/concentus instead.

**Comment by rcarubbi** [comment]
I solved using a command line tool via Process.Start

Thanks anyway!

Em 25 de mar de 2017 19:31, "Andrew Ward" <notifications@github.com>
escreveu:

> OK, that one worked. It's an OPUS file, which NVorbis cannot decode. You
> might try https://github.com/lostromb/concentus instead.
>
> On Fri, Mar 24, 2017 at 3:06 PM, Raphael Carubbi Neto <

**Comment by Mahdi-Farhani** [comment]
@rcarubbi would you please explain how do you solve it? I have the same problem.

**Comment by rcarubbi** [comment]
My need was recognize voice from telegram.

Telegram delivers a link to a oga file with the user's audio.

But Microsoft voice recognition only works with plain pcm wav files.

So I need to convert it before send.
My solution was use opusdec.exe.

Here my implementation... It not well written but works (it was just a loc)

https://github.com/rcarubbi/MicrosoftBotFrameworkTest/blob/master/WorkshopAtentoBot/WorkshopAtentoBot/Services/OgaToWavConverter.cs

Remember that you need to download opusdec.exe and include in your project.

If you have questions fell free to ask me.

Regards

Em Sáb, 14 de abr de 2018 06:57, Mahdi Farhani <notifications@github.com>
escreveu:

**Comment by Mahdi-Farhani** [comment]
@rcarubbi I find another way to convert Telegram Voice to Wav File.
I've used concentus.oggfile and RawSourceWaveStream

**Comment by ioctlLR** [comment]
Dropping this enhancement idea.
