### ISSUE TITLE
Add Matroska/WebM container support

### ISSUE THREAD

**Issue by ioctlLR** [ioctlLR/NVorbis#4]
Need working EBML parser (see [this CodePlex issue](https://nvorbis.codeplex.com/workitem/10) for a first-pass attempt) and a new IPacketProvider.

**Comment by libjared** [comment]
There's an EBML library on Nuget that I'm using (NEBML), with which I have been able to parse webms.

**Comment by ioctlLR** [comment]
Dropping this enhancement.
