### ISSUE TITLE
Will Vorbis Encoding Be Added?

### ISSUE THREAD

**Issue by Mosely** [ioctlLR/NVorbis#6]
Just curious as to whether the ability to encode Vorbis audio will be added.

**Comment by ioctlLR** [comment]
I have no plans to do so.  Encoding is a totally different animal than decoding, and you're much better off shelling-out to oggenc (I prefer the auTov build for better quality).  If someone wants to port it to C# and submit a pull request, I'll take it, though.

**Comment by Mosely** [comment]
Okay, thanks for the info.
