### ISSUE TITLE
Crash Playing Some OGG Files

### ISSUE THREAD

**Issue by stricq** [ioctlLR/NVorbis#7]
I have a number of ogg files that crash in NVorbis.  I've attached one.

[S_AmbWalla_SwordBattle02.zip](https://github.com/ioctlLR/NVorbis/files/185228/S_AmbWalla_SwordBattle02.zip)

**Comment by stricq** [comment]
NVorbis.VorbisCodebook.InitTree(DataPacket packet)
NVorbis.VorbisCodebook.Init(DataPacket packet)
NVorbis.VorbisStreamDecoder.LoadBooks(DataPacket packet)
NVorbis.VorbisStreamDecoder.TryInit()
NVorbis.VorbisReader.NewStream(Object sender, NewStreamEventArgs ea)
NVorbis.Ogg.ContainerReader.GatherNextPage()
NVorbis.Ogg.ContainerReader.Init()
NVorbis.VorbisReader.LoadContainer(IContainerReader containerReader)
NVorbis.VorbisReader..ctor(Stream stream, Boolean closeStreamOnDispose)
NAudio.Vorbis.VorbisWaveReader..ctor(Stream sourceStream)

**Comment by ioctlLR** [comment]
If you still need it, I've checked in a fix for this.  Sorry for taking so long to get a look at it.

**Comment by stricq** [comment]
Thanks for the fix.  Will you be making a new nuget package?

**Comment by ioctlLR** [comment]
It's now up on NuGet. :)
